finance/urls.py
from beckett.finance.models import *
from django.conf.urls.defaults import *
from beckett.finance.feeds import AllDonorCeos

urlpatterns = patterns('beckett.finance.views',
     (r'^robots.txt', 'robots'),
     url(r'^$', 'finance_index', name='finance_index'),
     url(r'^industries/$', 'industry_index', name='industry_index'),
     url(r'^ceos/$', 'ceo_index', name="ceo_index"),
     url(r'^ceos/ceos.json$', 'ceos_to_json', name="all_ceos_to_json"),
     url(r'^ceos/(?P<id_string>[\d-]*).json$', 'ceos_to_json', name="ceos_to_json"),
     url(r'^ceos/(?P<id_string>\d+)/edit$', 'edit_ceo', name='edit_ceo'),
     url(r'^donor/(?P<id_string>\d+)/delete$', 'delete_donor', name='delete_donor'),
     url(r'^zips/(?P<zip_code>\d{5}).json$', 'zips_to_json', name='zips_to_json'), 
     url(r'^zips/(?P<zip_code>\d{5})-data.json$', 'get_zip_data', name="zip_data"), 
     url(r'^candidates/(?P<id_string>\d+)/$', 'candidate_detail', name="candidate_detail"),
    url(r'^industries/(?P<object_id>\d+)/$', 'industry_detail', name="industry_detail", ),
)
urlpatterns += patterns('django.views.generic.list_detail',
    url(r'^ceos/(?P<object_id>\d+)/$', 'object_detail',  {'queryset': Ceo.donated.live(), }, "ceo_detail", ),
    url(r'^candidates/$', 'object_list',  {'queryset': Candidate.objects.all(), }, "candidate_index", ),
    url(r'^industries/(?P<object_id>\d+)/$', 'object_detail',  {'queryset': Industry.objects.all(), }, "industry_detail", ),
)


feeds = {
    'ceo_donors_all': AllDonorCeos,
}

urlpatterns += patterns('',
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
          {'feed_dict': feeds}),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from beckett.sitemaps import *
admin.autodiscover()

sitemaps = {
    'ceos': CeoSitemap,
    'industries': IndustriesSitemap,
    'candidates': CandidatesSitemap,
}
urlpatterns = patterns('',
    # Example:
    # (r'^beckett/', include('beckett.foo.urls')),

     (r'^', include('finance.urls')),
#    (r'^better_represent/', include('better_represent.urls')),
     (r'^feedback/', 'feedback.views.feedback'),
     (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
     (r'^google083c9739e43de133.html$', 'finance.views.verify'),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
     (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
)

finance/models.py
from django.contrib.gis.db import models
from beckett.polygons.models import Zip
from django.db.models import Sum, Q
from collections import defaultdict
import datetime



class Party(models.Model):
    name = models.CharField(max_length=24, unique=True)
    def _total_donations(self):
        candidates = self.candidate_set.all()
        total_donations = 0
        for candidate in candidates:
            total_donations += candidate.total_donations
        return total_donations
    total_donations = property(_total_donations)

    def __unicode__(self):
        return "%s" % self.name

class Candidate(models.Model):
    name = models.CharField(max_length=63, unique=True)
    party = models.ForeignKey(Party)

    @property    
    def total_donations(self):
        return self.donation_set.live().aggregate(Sum('donation_amount'))['donation_amount__sum']

    class Meta:
        ordering = ['-party', 'name']

    @models.permalink
    def get_absolute_url(self):
        return ('candidate_detail', [str(self.id)])


class Address(models.Model):
    address = models.TextField()
    address2 = models.TextField(null=True)
    state = models.CharField(max_length=2)
    city = models.CharField(max_length=63)
    zip = models.ForeignKey(Zip)
    point = models.PointField(srid='4326', null=True)
    objects = models.GeoManager()
    class Meta:
        unique_together = ('address', 'address2', 'city', 'state', 'zip')


class Industry(models.Model):
    name = models.CharField(max_length=63)

    @property   
    def total_donations(self):
        return sum([c.total_donations for c in self.ceo_set.all().select_related()])
    
    @property
    def total_donations_by_party(self):
        ceos = self.ceo_set.all().iterator()
        total_donations = defaultdict(int)
        for ceo in ceos:
            donations = ceo.donation_set.live().select_related().iterator()
            for donation in donations:
                total_donations[donation.party_name] += donation.donation_amount 
        return total_donations
    
    class Meta:
        ordering = ["name"]
    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('industry_detail', [str(self.id)])

class CeoManager(models.GeoManager):
    @property
    def total_donations(self):
        return sum([c.total_donations for c in  self.live()])

    
    def live(self):
        return super(CeoManager, self).get_query_set().filter(donor__isnull=False).distinct()

class Ceo(models.Model):
#add slug field with first name last name
    first_name = models.CharField(max_length=63)
    last_name = models.CharField(max_length=63)
    website = models.URLField()
    industry = models.ForeignKey(Industry, null=True)
    company_name = models.CharField(max_length=63, unique=False)
    company_address = models.ForeignKey(Address)
    ctime = models.DateTimeField(auto_now_add=True)
    mtime = models.DateTimeField(auto_now=True)
    donated = CeoManager()
    objects = models.GeoManager()

    def __unicode__(self):
        return self.first_name + " " + self.last_name
    
    def total_donations_by_candidate(self, candidate):
        return self.donation_set.live().filter(candidate_name=candidate.name).aggregate(Sum('donation_amount'))['donation_amount__sum']
    
    @property
    def total_donations(self):
        donors = self.donor_set.live().select_related()
        total_donations = 0
        for donor in donors:
            total_donations += donor.total_donations
        return total_donations
    
    @property
    def total_donations_by_party(self):
        parties = Party.objects.all()
        party_dict = defaultdict(int)
        for party in parties:
            total_donations = self.donation_set.live().filter(party_name = party.name).aggregate(Sum('donation_amount'))['donation_amount__sum']
            if total_donations == None:
                party_dict[party.name] = 0
            else:
                party_dict[party.name] += total_donations
        return party_dict 
    
    @property
    def leans(self):
        return max(self.total_donations_by_party, key = lambda a: self.total_donations_by_party.get(a))

    class Meta:
        #unique_together = ('company_name', 'last_name')
        ordering = ['last_name']

    @models.permalink
    def get_absolute_url(self):
        return ('ceo_detail', [str(self.id)])

    @models.permalink
    def get_edit_url(self):
        return ('edit_ceo', [str(self.id)])

class DonorManager(models.GeoManager):
    def live(self):
        return self.filter(Q(approved=True, operation='A') | Q(approved=False, operation='D'))

class Donor (models.Model):
    choices = ( ('A', 'add'), ('D', 'delete') )
    operation = models.CharField(max_length=1, choices=choices, default='A')
    approved = models.BooleanField(default=False)
    ceo = models.ForeignKey(Ceo)
    first_name = models.CharField(max_length=63)
    last_name = models.CharField(max_length=63)
    donor_address = models.ForeignKey(Address)
    ctime = models.DateTimeField(auto_now_add=True)
    mtime = models.DateTimeField(auto_now=True)
    objects = DonorManager()
    
    @property
    def total_donations(self):
        return self.donation_set.live().aggregate(Sum('donation_amount'))['donation_amount__sum']

    class Meta:
        unique_together = ('donor_address','first_name', 'last_name')

    def save_and_approve(self):
        self.operation = 'A'
        self.approved = True
        for donation in self.donation_set.all():
            donation.save_and_approve()
        self.save()

    def delete_soft(self):
        self.operation = 'D'
        self.approved = False
        for donation in self.donation_set.live():
            donation.delete_soft()
        self.save()

class DonationManager(models.GeoManager):
    use_for_related_fields = True
    def live(self):
        return self.filter(Q(approved=True, operation='A')  | Q(approved=False, operation='D'))
    
    @property
    def total_donations_by_party(self):
        parties=Party.objects.all()
        party_dict={}
        for party in parties:
            try:
                party_dict[party.name] += Donation.objects.live().filter(party_name=party.name).aggregate(Sum('donation_amount'))['donation_amount__sum']
            except KeyError:
                party_dict[party.name] = Donation.objects.live().filter(party_name=party.name).aggregate(Sum('donation_amount'))['donation_amount__sum']
        return party_dict
    
    @property
    def total_donations(self):
        return Donation.objects.live().aggregate(Sum('donation_amount'))['donation_amount__sum'] 
                    


class Donation(models.Model):
    ##### Crowd Sourcing!!!! ##########
    choices = ( ('A', 'Added'), ('D', 'Deleted') )
    operation = models.CharField(max_length=1, choices=choices, default='A')
    approved = models.BooleanField(default=False)
    candidate = models.ForeignKey(Candidate)
    donor = models.ForeignKey(Donor)
    ceo = models.ForeignKey(Ceo)
    candidate_name = models.CharField(max_length=63, null=True)
    party_name = models.CharField(max_length=24, null=True)
    donation_amount = models.IntegerField()
    donation_date = models.DateField()
    ctime = models.DateTimeField(auto_now_add=True)
    mtime = models.DateTimeField(auto_now=True)
    objects = DonationManager()

    class Meta:
        unique_together = ('candidate', 'donor', 'donation_amount', 'donation_date')
        ordering = ['-donation_date']

    def __unicode__(self):
        return "Donation to %s for %s" % (self.candidate_name,self.ceo)

    @models.permalink
    def get_delete_url(self):
        return ('delete_donation', [str(donation.id)])

    def save(self, force_insert=False, force_update=False):
        # denormalization
        self.ceo = self.donor.ceo
        self.candidate_name = self.candidate.name
        self.party_name = self.candidate.party.name
        super(Donation, self).save(force_insert, force_update)
    
    def save_and_approve(self):
        self.operation = 'A'
        self.approved = True
        self.save()

    def delete_soft(self):
        self.operation = 'D'
        self.approved = False
        self.save()


###########################
#      Rate Limiter       #
###########################

class RequestRateManager(models.Manager):
	def clean_expired(self):
		"""Purges old entries from database.

		If you use max_value's greater than 600 (seconds, ten minutes),
		change the following line."""
		l_time = datetime.datetime.now() - datetime.timedelta(seconds = 600)
		self.get_query_set().filter(last_update__lt=l_time).delete()

class RequestRate(models.Model):
	"""Implements a rate limit per IP.

	value is increased at every request by the amount the request specifies,
	which is meant to be the average number of seconds until the same
	request could be made again.

	value decreases at a rate of 1 per second until it is a 0.
	"""
	name = models.CharField(max_length=20)
	ipaddr = models.IPAddressField(blank=True, null=True)
	last_update = models.DateTimeField(auto_now_add=True)
	value = models.FloatField()

	objects = RequestRateManager()

	def update(self):
		this_update = datetime.datetime.now()
		td = this_update - self.last_update
		time_delta_sec = (float(td.days) * 3600.0 * 60.0 + float(td.seconds) +
			float(td.microseconds) / 1000000.0)
		self.value -= time_delta_sec
		if self.value < 0:
			self.value = 0
		self.last_update = this_update
	def request(self, seconds, max_value):
		self.update()
		if self.value + seconds < max_value:
			self.value += seconds
			self.save()
			return True
		else:
			self.save()
			return False

finance/forms.py
from django.forms.models import ModelForm
from django.forms.fields import Field

class DonationDeleteForm(ModelForm):
    class Meta:
        model=Donation
        fields=None

templates/finance/base_finance.html
{% extends "base.html" %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/css/finance.css">
{% endblock %}
{% block title %}
CEO Politics - Corporate Donations in the 2008 Presidential Race - 
{% endblock %}
{% block extra_header %}
    <div class="container">
        <div class="column span-4">
       	    <a href="/"><img src="{{ MEDIA_URL }}/images/democracy.png" alt="Democracy!"></a>
        </div>
        <div id="header_note" class="column span-2">
        <h2>Corporate Donations in the 2008 Presidential Race</h2>
        <b><a href="{% url candidate_index %}">By Candidate</a>, <a href="{% url ceo_index %}">By Ceo</a>, <a href="{% url industry_index %}">By Industry</a>.</b>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% block map %}
    </div>
    <div id="map_canvas"></div>
    <div class="container">
    {% endblock %}
        <div class="column span-4">
        {% block left %}

        {% endblock %}
        </div>
        <div class="column span-2">
        {% block legend %}
        The circles (<img src="{{ MEDIA_URL }}/images/blue_circle.png" style="display:inline; position:relative; top:4px;" width="16" height="16" /><img src="{{ MEDIA_URL }}/images/red_circle.png" style="display:inline; position:relative; top:4px;" width="16" height="16" />) above are each CEO's relative share of the total financial contributions. The split bars (<img src="{{ MEDIA_URL }}/images/splitbars.png" style="display:inline" />) under each CEO's name, on the left, are how each CEO's donations break down.  
        {% endblock %}
        {% block right %}

        {% endblock %}
        </div>
    </div>
{% endblock %}

templates/finance/candidate_detail.html
{% extends "finance/ceo_list.html" %}
{% block title %}CEO Politics - Corporate Donations in the 2008 Presidential Race - {{ candidate.name }}{% endblock %}
{% load extras %}
{% block left %}
<ul class="chartlist">
    <li>
        <h1>{{ candidate.name }}</h1>
        <span class="count">${{candidate.total_donations}}</span>
    </li>
</ul>
{{ block.super }}
{% endblock %}

templates/finance/candidate_list.html
{% extends "finance/base_finance.html" %}
{% block title %}{{ block.super }}All Candidates{% endblock %}
{% load extras %}
{% block content %}
<div class="container">
<ul class="chartlist">

{% for candidate in object_list|dictsortreversed:"total_donations" %}
<li>
    <a href="{% url candidate_detail candidate.id %}">{{ candidate.name }}</a>
    <span class="count">${{candidate.total_donations}}</span> 
<li>
{% endfor %}
</ul>
</div>
{% endblock %}

templates/finance/ceo_detail.html
{% extends "finance/base_finance.html" %}
{% load extras %}
{% block title %}
{{ block.super }} {{ object.first_name }} {{ object.last_name }} 
{% endblock %}
{% block extra_js %}
    <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAo1FSG5FcFxwjbAvjzMn_DRSwTQmyLrXXUnBi9bfEvTXJ8w45MRRjT2_c29y7wQB1MF7h5AQU-ukxrw" type="text/javascript"></script>
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("jquery", "1", {uncompressed:true});
    </script>
    <script>
    var icon_img = { 'R': '{{ MEDIA_URL }}/images/red_circle.png', 'D': '{{ MEDIA_URL }}/images/blue_circle.png' };
    var coords = []
    var map;
    var leans;
    function initialize() {
        if (GBrowserIsCompatible()) {
            map = new GMap2(document.getElementById("map_canvas"));
            map.addControl(new GLargeMapControl());
            $.getJSON("{% url ceo_index %}{{object.id}}-.json", 
                function(data){
                        item = data[0];
                        var total_donations = 956488;
                        var icon = new GIcon(G_DEFAULT_ICON);
                        icon.image = icon_img[item.icon];
                        icon.shadow = '';
                        icon.iconSize = new GSize(item.total/total_donations * 10000 * 3,  item.total/total_donations * 10000 * 3);
                        icon.iconAnchor = new GPoint(icon.iconSize.width/2, icon.iconSize.height/2);
                        markerOptions = { icon: icon, title: item.title};
                        var lat_lon = new GLatLng(item.pointlat,item.pointlong);
                        map.setCenter(lat_lon, {% block scale %}12{% endblock%}); 
                        map.addOverlay(new GMarker(lat_lon, markerOptions));
                });
            $.ajax({
                type: 'GET', 
                url:"{% url zip_data object.company_address.zip.code %}", 
                async:false, 
                success: function (msg){ showzip(msg) }
            });
        }
    } 
    function showzip(leans){
        var leans_dict = { 'R': ['Republican', '#812526', '#815354'], 'D': ['Democratic', '#182969', '#394369'] };
        if(leans != ''){
            $("#leans").html(", which leans <span class ='" + leans + "'>"  + leans_dict[leans][0] +"</span> in total campaign financing");
            $.getJSON("{% url zips_to_json object.company_address.zip.code %}", function (data){
                    $.each(data.coordinates, function() {
                        $.each(this, function(){
                                $.each(this, function(){
                                        coords.push(new GLatLng(this[1], this[0]));
                                    });
                                });
                            });
                        poly = new GPolygon(coords, leans_dict[leans][1], 2, 1, leans_dict[leans][2], 0.2);
                        map.addOverlay(poly);
                });
        }

    }
    $("document").ready(function () {
        initialize();
        {% block extra_init_map %}{% endblock %}
    });
    </script>
{% endblock %}

{% block left %}
    <ul>
        {% ceo_generic object %}
    </ul>
{% endblock %}

{% block legend %}
<span class="{{object.leans}}">{{ object.first_name }} {{object.last_name}}</span> works in zip code {{ object.company_address.zip.code }} ({{ object.company_address.city }}, {{ object.company_address.state  }})<span id="leans"></span>.
    <p><a href="{{ object.get_edit_url }}" class="small" rel="nofollow">(edit this ceo)</a></p>
{% endblock %}

templates/finance/ceo_generic.html
{% load extras %}
{% if ceo.total_donations %}
    <li class="ceo-item">
            <ul class="chartlist">
                <li>
               <h3><a href="{% url ceo_detail ceo.id %}">{{ ceo.first_name }} {{ ceo.last_name }}</a></h3>
                <span class="count">${{ceo.total_donations}}</span> 
                {% splitbar ceo.total_donations_by_party ceo.total_donations %}
                </li>
            </ul>
           <h4><a href="http://{{ceo.website}}">{{ ceo.company_name }}</a> ({{ ceo.company_address.city }}, {{ ceo.company_address.state }})
           {% if ceo.industry.id %}
                <br />(<a href="{% url industry_detail ceo.industry.id %}">{{ ceo.industry }}</a>)
           {% endif %}
           </h4>
           <table>
                <tr>
                    <th>
                        Candidate
                    </th>
                    <th>
                       Amount 
                    </th>
                    <th>
                        Date
                    </th>
                </tr>

                {% for donor in ceo.donor_set.all %} 
                    {% for donation in donor.donation_set.all %}
                    <tr>
                        <td><a href="{{ donation.candidate.get_absolute_url}}">{{ donation.candidate.name }}</a></td>
                        <td><span class="{{ donation.candidate.party.name}}">${{ donation.donation_amount }}</span></td>
                        <td>{{ donation.donation_date|date:"F jS, Y" }}</td>
                    </tr>
                    {% endfor %}
                {% endfor %}
            </table>
            
    <li>
{% endif %}

templates/finance/ceo_list.html
{% extends "finance/base_finance.html" %}
{% load extras %}
{% block extra_js %}
{% map_ceos ceo_list.object_list %}
{% endblock %}
{% block title %}
    {{block.super}} All Ceos (Page {{ ceo_list.number }})
{% endblock %}

    {% block left %}
    <ul>
    {% for ceo in ceo_list.object_list %}
        {% ceo_generic ceo %}
    {% endfor %}
    </ul>
    {% endblock %}
    {% block right %}
    <div class="pagination">
        <span class="step-links">
            {% if ceo_list.has_previous %}
                <a href="?page={{ ceo_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page <b>{{ ceo_list.number }}</b> of <b>{{ ceo_list.paginator.num_pages }}</b>.
            </span>

            {% if ceo_list.has_next %}
                <a href="?page={{ ceo_list.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
    {% endblock %}

templates/finance/delete_donor.html
<span class="success">Thanks for your help! Try again in a week!</a>

templates/finance/delete_donor_exceeded.html
<span class="error">You've already made your edit this week. Check back soon!</span>

templates/finance/edit_ceo.html
{% extends "finance/ceo_detail.html" %}
{% load extras %}

{% block title %}
{{ block.super }} - Editing
{% endblock %}
{% block extra_js %}
    <script>
    function show_donors(){
    {% for donor in donors %}
        icon = new GIcon(G_DEFAULT_ICON);
        icon.image = "{{ MEDIA_URL }}/images/{{ forloop.counter }}.png";
        icon.shadow = '';
        icon.iconSize = new GSize(16,16);
        icon.iconAnchor = new GPoint(icon.iconSize.width/2, icon.iconSize.height/2);

        lat_lon = new GLatLng({{donor.donor_address.point.x}}, {{donor.donor_address.point.y}});
        mrkr = new GMarker(lat_lon, 
                            { icon: icon, title: "{{ object.first_name }} {{ object.last_name }}" }
                        );
        map.addOverlay(mrkr);
    {% endfor %}
    }
    </script>
    {{ block.super }}
{% endblock %}
{% block extra_init_map %}
    $("a.delete_donor").click( function (e) {
        $(this).replaceWith("<br />Thanks for the heads up.");
        $("#msg").load($(this).attr('href'));
        e.preventDefault();
        });
    setTimeout("show_donors()", 1000); 
{% endblock %}
{% block scale %}
10
{% endblock %}

{% block left %}
{{ block.super }}
<h2>Donations on Record for {{ object.first_name }} {{ object.last_name }}</h2>
<p>
Something amiss? Because I have faith in you to do the right thing, you can choose to delete each of {{ object.first_name }} {{ object.last_name }}'s records (changes will appear after approval). I'm counting on you to tell me where I messed up.
</p>
<div id="msg"></div> 
    {% for donor in donors %}
        <b>Donation made from:</b> <img src="{{ MEDIA_URL }}/images/{{ forloop.counter }}.png" style="display:inline; position:relative; top: 3px" /> {{ donor.donor_address.city }}, {{ donor.donor_address.state }}
                <span class="small">
                {% if donor.approved %}
                    <a href="{% url delete_donor donor.id %}" class="delete_donor" rel="nofollow">Delete</a>
                {% else %}
                    <br />Pending approval to {{ donor.get_operation_display }}.
                {% endif %}
                </span> 
    <table>
        <tr>
            <th>
               Candidate
            </th>
            <th>
                Amount
            </th>
            <th>
                Date
            </th>
        </tr>
        {% for donation in donor.donation_set.live %}
        <tr> 
            <td>{{ donation.candidate_name  }}</td>
            <td><span class="{{ donation.party_name }}">
            {{ donation.donation_amount }}</span></td>
            <td>{{donation.donation_date|date:"F jS, Y"}}</td>
        </tr>
        {% endfor %}
    </table>
    {% endfor %}
</form>
{% endblock %}

templates/finance/index.html
{% extends "finance/base_finance.html" %}
{% block title %}
{{ block.super }} All CEO Donations
{% endblock %}
{% load extras %}
{% block extra_js %}
    <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAo1FSG5FcFxwjbAvjzMn_DRSwTQmyLrXXUnBi9bfEvTXJ8w45MRRjT2_c29y7wQB1MF7h5AQU-ukxrw" type="text/javascript"></script>
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("jquery", "1");
    </script>
    <script>
    var map;
    var geoXml;
    var mgr;
    var icon_img = { 'R': '{{ MEDIA_URL }}/images/red_circle.png', 'D': '{{ MEDIA_URL }}/images/blue_circle.png' };
    function initialize() {
        if (GBrowserIsCompatible()) {
            map = new GMap2(document.getElementById("map_canvas"));
            map.setCenter(new GLatLng(37.809,-96.555), 4); 
            map.addControl(new GLargeMapControl());
        }
    } 
    function setupAllMarkers(data){
        var total_donations = 956488;
        $.each(data,
            function(i, item){
                var icon = new GIcon(G_DEFAULT_ICON);
                icon.image = icon_img[item.icon];
                icon.shadow = '';
                icon.iconSize = new GSize(item.total/total_donations * 10000,  item.total/total_donations * 10000);
                icon.iconAnchor = new GPoint(icon.iconSize.width/2, icon.iconSize.height/2);
                markerOptions = { icon: icon };
                var lat_lon = new GLatLng(item.pointlat,item.pointlong);
                var mrkr = new GMarker(lat_lon, markerOptions);
                GEvent.addListener(mrkr, "click", function() {
                    window.location = item.url;
                });
                map.addOverlay(mrkr);
        });
    }
    $("document").ready(function () {
        $.getJSON("{% url all_ceos_to_json %}", setupAllMarkers);
        initialize();
    });
    </script>
{% endblock %}
{% block content %}
    <div id="map_canvas"></div>
    <div class="container">
        <div class="column span-6">
        <h1 id="total">${{ donations }} in total public financing <img src="{{ MEDIA_URL }}/images/chart.png" /></h1>
        {% for k,v in donations_by_party.items %}
            <h2 class="{{k}}">${{v}}</h2>
        {% endfor %}
        <ul class="chartlist">
        <li>
        {% splitbar donations_by_party donations %}
        </li>
        </ul>
        </div>
    </div>
{% endblock %}

templates/finance/industry_detail.html
{% extends "finance/base_finance.html" %}
{% load extras %}
{% block title %}
{{ block.super }} {{ object.name }} (Page {{ ceo_list.number }})
{% endblock %}
{% block extra_js %}
{% map_ceos ceo_list.object_list %}
{% endblock %}
{% block left %}
<ul class="chartlist">
    <li>
        <h1>{{ object.name }}</h1>
        <span class="count">${{object.total_donations}}</span> 
        {% splitbar object.total_donations_by_party object.total_donations %}
    <li>
</ul>
<ul>
{% for ceo in ceo_list.object_list %}
    {% ceo_generic ceo %}
{% endfor %}
</ul>
{% endblock %}
{% block right %}
<div class="pagination">
    <span class="step-links">
        {% if ceo_list.has_previous %}
            <a href="?page={{ ceo_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page <b>{{ ceo_list.number }}</b> of <b>{{ ceo_list.paginator.num_pages }}</b>.
        </span>

        {% if ceo_list.has_next %}
            <a href="?page={{ ceo_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/finance/industry_list.html
{% extends "finance/base_finance.html" %}
{% load extras %}
{% load cache %}
{% block title %}
{{ block.super }} All Industries
{% endblock %}
{% block content %}
<div class="container">
<ul class="chartlist">
{% cache 120000 all_industries %}
{% for industry in objects %}
<li>
    <a href="{% url industry_detail industry.id %}">{{ industry.name }}</a>
    <span class="count">${{industry.total_donations}}</span> 
    {% splitbar industry.total_donations_by_party industry.total_donations %}
<li>
{% endfor %}
{% endcache %}
</ul>
</div>
{% endblock %}

templates/finance/split_bar.html
    <div class="split-bar">
    {% for k,v in split.items %}
        <span class="index {{k}}" style="width:{% widthratio v total 100 %}%">{% widthratio v total 100%}</span>
    {% endfor %} 
    </div>